./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/wave 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/audikw1 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/ldoor 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/rgg_n_2_17_s0 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Wiki-Vote 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/as-22july06 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/p2p-Gnutella04 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/kron_g500-simple-logn16 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Slashdot0811 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Slashdot0902 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/soc-Epinions1 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/cond-mat-2005 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/cit-Patents 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/web-Google 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/cage15 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/web-BerkStan 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/uk-2002 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/WikiTalk 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Email-EuAll 300 1 >> DPtest.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/333SP 300 1 >> DPtest.txt
