./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/coPapersCiteseer 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/eu-2005 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/cnr-2000 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/rgg_n_2_24_s0 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/rgg_n_2_23_s0 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/rgg_n_2_17_s0 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/rgg_n_2_19_s0 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/cond-mat-2005 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/belgium.osm 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/caidaRouterLevel 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/333SP 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/ecology1 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/rgg_n_2_20_s0 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/preferentialAttachment 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/rgg_n_2_22_s0 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/coAuthorsDBLP 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/uk-2002 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/citationCiteseer 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/smallworld 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/wave 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/as-22july06 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/coPapersDBLP 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/coAuthorsCiteseer 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/in-2004 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/rgg_n_2_21_s0 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/luxembourg.osm 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/audikw1 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/ldoor 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/kron_g500-simple-logn16 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/G_n_pin_pout 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/DIMACS10/cage15 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/web-arabic-2005.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/web-baidu-baike.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/rec-dating.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-dogster.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/hugebubbles-00020.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/delaunay_n22.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/tech-as-skitter.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/twitter_mpi.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-LiveMocha.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-lastfm.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/inf-roadNet-PA.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/dbpedia-link.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-youtube.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/ca-dblp-2012.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/bn-human-BNU_1_0025865_session_1-bg.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/ca-coauthors-dblp.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/web-wikipedia2009.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-livejournal.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/friendster.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/rgg_n_2_24_s0.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/rec-libimseti-dir.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/sc-ldoor.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/inf-road-usa.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/socfb-B-anon.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/rt-retweet-crawl.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-twitter-higgs.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/inf-europe_osm.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-flickr.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/sc-shipsec5.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/sc-shipsec1.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/web-wikipedia_link.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/delaunay_n23.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/hugetrace-00010.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/delaunay_n24.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-flickr-und.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/web-it-2004.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-livejournal-user-groups.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-digg.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/sc-msdoor.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/web-uk-2005.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/sc-pwtk.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/wikipedia_link_en.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/inf-germany_osm.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/socfb-uci-uni.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/tech-ip.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-youtube-snap.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/bn-human-BNU_1_0025865_session_2-bg.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-orkut-dir.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-ljournal-2008.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/socfb-A-anon.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-FourSquare.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-delicious.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/ca-hollywood-2009.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-pokec.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-orkut.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/rec-epinions.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/sc-rel9.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/web-wikipedia-growth.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/rgg_n_2_23_s0.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-flixster.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-sinaweibo.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/soc-buzznet.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/hugetrace-00020.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/channel-500x100x100-b050.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/Network_Repository/inf-roadNet-CA.mtx 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/.DS_Store 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/2-Insertions_3.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/3-Insertions_3.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/anna.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/C2000.5.clq 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/C4000.5.clq 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/david.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC1000.1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC1000.5.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC1000.9.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC125.1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC125.5.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC125.9.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC250.1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC250.5.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC250.9.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC500.1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC500.5.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJC500.9.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJR500.1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJR500.1c.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJR500.1c.col.b 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/DSJR500.5.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/flat1000_50_0.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/flat1000_60_0.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/flat1000_76_0.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/flat300_20_0.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/flat300_26_0.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/flat300_28_0.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/fpsol2.i.1 copy.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/fpsol2.i.1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/fpsol2.i.2.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/fpsol2.i.3.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/games120.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/homer.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/huck.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/inithx.i.1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/inithx.i.2.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/inithx.i.3.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/jean.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/latin_square_10.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_15a.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_15b.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_15c.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_15d.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_25a.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_25b.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_25c.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_25d.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_5a.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_5b.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_5c.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/le450_5d.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/miles1000.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/miles1500.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/miles250.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/miles500.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/miles750.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/mug100_1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/mug100_25.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/mug88_1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/mug88_25.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/mulsol.i.1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/mulsol.i.2.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/mulsol.i.3.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/mulsol.i.4.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/mulsol.i.5.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/myciel3.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/myciel4.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/myciel5g.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/myciel6g.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/myciel7g.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/qg.order30.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/qg.order40.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/qg.order60.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen10_10.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen11_11.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen12_12.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen13_13.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen14_14.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen15_15.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen16_16.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen5_5.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen6_6.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen7_7.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen8_12.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen8_8.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/queen9_9.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/school1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/school1_nsh.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/wap05a.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/wap06a.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/wap07a.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/wap08a.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/zeroin.i.1.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/zeroin.i.2.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MSCP/conventional_benchmark/zeroin.i.3.col 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Cit-HepPh 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Amazon0601 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Slashdot0902 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Slashdot0811 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/p2p-Gnutella24 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/p2p-Gnutella30 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/WikiTalk 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/web-Stanford 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Amazon0302 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/web-NotreDame 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Amazon0312 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Amazon0505 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/cit-Patents 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/p2p-Gnutella25 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/p2p-Gnutella04 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/soc-Epinions1 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/web-BerkStan 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/p2p-Gnutella31 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Cit-HepTh 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Email-EuAll 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/Wiki-Vote 7200 1 >> output.txt
./ReduceColor /home/wyy/benchmark/MDS/SNAP/web-Google 7200 1 >> output.txt
